### ISSUE TITLE
复杂对象存储redis

### ISSUE THREAD

**Issue by loserwangzhi** [AobingJava/JavaFamily#22]
文中提到，有些仔喜欢把复杂对象也转换成JsonString存储，实不相瞒，我就是那个仔，哈哈哈哈。比如在登陆的时候将用户的基本信息（user）以及权限(permission) 一起转成JsonString存缓存了，我想知道更好的做法是什么。

**Comment by AobingJava** [comment]
Hash 用来存储对象会好点
