### ISSUE TITLE
招聘贴：阿里巴巴消息业务/基础团队招聘（校招/社招）

### ISSUE THREAD

**Issue by hepin1989** [AobingJava/JavaFamily#23]
我们团队都是Java哈，大家刷好题了就可以随时来碾压我们了。欢迎大家加入。
招聘, 微信：kerisle，邮箱：hepin.p#alibaba-inc.com
![image](https://user-images.githubusercontent.com/501740/76274299-353fc700-62bb-11ea-8e9d-2a0c080ab336.png)

**Comment by shuwen9** [comment]
老哥，阿里简历初筛没过是怎么回事



在 2020-03-09 15:49:45，"kerr" <notifications@github.com> 写道：

我们团队都是Java哈，大家刷好题了就可以随时来碾压我们了。欢迎大家加入。

**Comment by hepin1989** [comment]
@shuwen9 您好，您的简历发送给了我吗？具体的联系人是？可以邮件给我哈

**Comment by shuwen9** [comment]
是在别的平台投的，然后发邮件说初筛没过



在 2020-03-23 12:54:06，"kerr" <notifications@github.com> 写道：

@shuwen9 您好，您的简历发送给了我吗？具体的联系人是？可以邮件给我哈
