### ISSUE TITLE
关于HashMap文章中的一个小建议

### ISSUE THREAD

**Issue by JachinDu** [AobingJava/JavaFamily#25]
丙哥，读了你的HashMap.md感觉收获满满，不过有两个地方我想提一下：

1. 文中 “因为在使用不是2的幂的数字的时候，Length-1的值是所有二进制位全为1，这种情况下，index的结果等同于HashCode后几位的值。”一句中应该是“是2的幂”，Length-1才会全是1吧。
2. “只要输入的HashCode本身分布均匀，Hash算法的结果就是均匀的。” 这里我觉得可以加上HashMap源码中对hashCode值的一个操作。
源码中对key的hash方法：

```java 
static final int hash(Object key) {
        int h;
        return (key == null) ? 0 : (h = key.hashCode()) ^ (h >>> 16);
    }
```
其中将原32位hashcode与其右移16位后的结果做了异或，为了让高16位也参与到“让hashcode分布更均匀”中，这样更能让hashcode分布均匀吧。
（第一次提issue，如有不妥，望丙哥告知🤓

**Comment by Dcwjh** [comment]
> 丙哥，读了你的HashMap.md感觉收获满满，不过有两个地方我想提一下：
> 
> 1. 文中 “因为在使用不是2的幂的数字的时候，Length-1的值是所有二进制位全为1，这种情况下，index的结果等同于HashCode后几位的值。”一句中应该是“是2的幂”，Length-1才会全是1吧。
> 2. “只要输入的HashCode本身分布均匀，Hash算法的结果就是均匀的。” 这里我觉得可以加上HashMap源码中对hashCode值的一个操作。
>    源码中对key的hash方法：
> 
> ```java
> static final int hash(Object key) {
>         int h;
>         return (key == null) ? 0 : (h = key.hashCode()) ^ (h >>> 16);
>     }
> ```
> 
> 其中将原32位hashcode与其右移16位后的结果做了异或，为了让高16位也参与到“让hashcode分布更均匀”中，这样更能让hashcode分布均匀吧。
> （第一次提issue，如有不妥，望丙哥告知🤓

好巧，我也注意到这个点了。
