### ISSUE TITLE
先点个赞

### ISSUE THREAD

**Issue by queenns** [AobingJava/JavaFamily#3]
先点赞
所有的都看了，风格杠杠的
1.在看秒杀这篇的时候有lua脚本，突然想到怎么调用的lua脚本
2.类似于秒杀这篇文章的话是否可以有一个小的demo,可以代码思路整个流程
大家水平都不一样，知道的不知道的，一些关键地方是否可以添加必要代码或者demo的github链接
最近也在排查一些redis涉及的问题，所以想到作者是否也可以分享一些自己实际场景的一些使用或者问题等
例如说:jedis或者lettuce框架选型啊，使用中的问题啊
以上都是本人歪歪出来的，作者的想法肯定比我好，或者精力比较有限，看看是否有必要加一类这些东西

过来主要是点赞的

**Comment by luokun1995** [comment]
能不能不要频繁的发邮件啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"敖丙"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 下午3:25
收件人:&nbsp;"AobingJava/JavaFamily"<JavaFamily@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [AobingJava/JavaFamily] 先点个赞 (#3)




Closed #3.
