### ISSUE TITLE
布隆过滤器(BloomFilter).md中描述的应用场景应该是缓存穿透，而不是缓存击穿吧。

### ISSUE THREAD

**Issue by cocolee1019** [AobingJava/JavaFamily#37]
“
那应用的场景在哪里呢？一般我们都会用来防止缓存击穿（如果不知道缓存击穿是啥的小伙伴不要着急，我已经帮你准备好了，传送门 ↓ ）

简单来说就是你数据库的id都是1开始然后自增的，那我知道你接口是通过id查询的，我就拿负数去查询，这个时候，会发现缓存里面没这个数据，我又去数据库查也没有，一个请求这样，100个，1000个，10000个呢？你的DB基本上就扛不住了
”

**Comment by AobingJava** [comment]
是的 笔误
