### ISSUE TITLE
大佬，能不能提个问题。。

### ISSUE THREAD

**Issue by SiriusQiu** [AobingJava/JavaFamily#45]
大佬问个问题。。。《java并发编程的艺术》里读到一句话：“当写一个volatile变量时，JMM会把该线程对应的本地内存的共享变量刷新到主内存”。这边的共享变量，是指被volatile修饰的共享变量，还是指该线程所有改动后的共享变量。

**Comment by SiriusQiu** [comment]
volatile的写指令后有一个storeload内存屏障，storeload：store1;StoreLoad;load2;在load2及之后要读取的数据被访问之前，保证store1的写入对所有处理器可见。所以只保证store1可见是吗，store1之前的store指令是否保证可见呢

**Comment by a1309896003** [comment]
111
