### ISSUE TITLE
描述错误

### ISSUE THREAD

**Issue by gpqhl0071** [AobingJava/JavaFamily#46]
![image](https://user-images.githubusercontent.com/8787216/89015348-752a4800-d349-11ea-929d-27e7367c87c7.png)

文章地址：https://mp.weixin.qq.com/s/3PNWmtS-bEZgZjd9wyMiDA

该文章应该：如果initialCapacity **>** 0，就创建一个新的长度是initialCapacity的数组

**Comment by onemsg** [comment]
Why is this issue not closed？
