### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by Skqing** [AobingJava/JavaFamily#5]
1. 图片裂了 https://camo.githubusercontent.com/44372e3cddff9dfbf0336cdafa19b7cd71208e46/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323031392f31312f31352f313665366564643338626335613265363f773d36393826683d37393926663d706e6726733d313234343330

2. ##面试结束 应该是 ## 面试结束吧，格式不对，好几篇文章的无序列表都有这个错误

**Comment by AobingJava** [comment]
我 都是用本地的markdown工具 写的 直接复制进去了，不同的markdown 可能格式不一样
