### ISSUE TITLE
Spring循环依赖文章有一处错误

### ISSUE THREAD

**Issue by LukeyLi** [AobingJava/JavaFamily#51]
地址: https://mp.weixin.qq.com/s/kS0K5P4FdF3v-fiIjGIvvQ
错误地方：“为了测试循环依赖的解决情况跟注入方式的关系，我们做如下四种情况的测试”，最后两种情况循环依赖是否被解决情况有误

**Comment by LukeyLi** [comment]
最后你描述的两个情况是同一种情况，循环依赖解决结果不一

**Comment by goolulu** [comment]
没写错，这个跟bean初始化顺序、三级缓存有关

**Comment by LukeyLi** [comment]
@goolulu 文章尾处一道思考题。“AB相互依赖（循环依赖）A中注入B的方式为setter方法，B中注入A的方式为构造器”
与“AB相互依赖（循环依赖），B中注入A的方式为setter方法，A中注入B的方式为构造器”。看下表格， 这个就是一个情况，这两句话是等同的。

**Comment by goolulu** [comment]
> 与“AB相互依赖（循环依赖），B中注入A的方式为setter方法，A中注入B的方式为构造器”。看下表格， 这个就是一个情况，这两句话是等同的。

不同，写一下就知道了。前面文章有解释，你没认真看
