### ISSUE TITLE
谁是原创呢

### ISSUE THREAD

**Issue by 4379711** [AobingJava/JavaFamily#56]
我看了你的[秒杀系统2.0](https://mp.weixin.qq.com/s/KWb3POodisbOEsQVblsoGw),发现超卖并没有解释清楚,于是去google了一圈,发现[这个博客](https://www.cnblogs.com/yaopengfei/p/12418229.html),这个博客在文末标注了原创声明,那么谁是原创呢?你们是同一个人?

**Comment by Arisono** [comment]
这个面试资料全是抄袭来的，知道就好。不用大惊小怪。
