### ISSUE TITLE
Bloom Filter讲解错误

### ISSUE THREAD

**Issue by zlp1992** [AobingJava/JavaFamily#6]
Bloom Filter应该是用于缓存穿透的？此外这边文章里内容说的缓存击穿的概念根本就是缓存穿透的
![image](https://user-images.githubusercontent.com/11548492/69334246-4675b100-0c95-11ea-8d0c-00da3ab14845.png)
![image](https://user-images.githubusercontent.com/11548492/69334320-6b6a2400-0c95-11ea-84bc-363d8eb83841.png)

**Comment by AobingJava** [comment]
get
