### ISSUE TITLE
全是相互抄

### ISSUE THREAD

**Issue by myclouderhem** [AobingJava/JavaFamily#71]
全是买课推广关注公众号

**Comment by zyfsuzy** [comment]
内卷开始，也没办法

**Comment by chenhaode** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by linghongbang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
